### ISSUE TITLE
Add sprint text box not 'submittable' (cant press enter to submit)

### ISSUE THREAD

**Issue by leavinit** [adj-dev/final-project#62]
Would be nice to hit enter after typing in the new sprint name and have it be submitted

**Comment by adj-dev** [comment]
It is submittable if the tiny "plus" symbol is pressed. but will add submit upon hitting 'enter' soon.

**Comment by leavinit** [comment]
Excellent.

**Comment by leavinit** [comment]
Also consider having the modals be closeable with the Esc key.  More of a feature request than an issue, Smooths the u.i flow if someone opens a modal that they didnt mean to, then wants to exit it w/o entering anything.  Cool to set that idea on the back-burner if it's too intricate (key handling)

**Comment by adj-dev** [comment]
I'll throw that esc idea onto the back-burner. too much crucial functionality needs to be completed first, but I do think that's a good idea. enter button now works.
