### ISSUE TITLE
.sprint-item text (text/date/status) needs formatting

### ISSUE THREAD

**Issue by leavinit** [adj-dev/final-project#70]
sprint items timestamp needs to be formatted in a way thats more human readable.  Spacing and placement of the status need attention as well.

**Comment by adj-dev** [comment]
I totally agree. Saving this issue for tomorrow so Nhu and I can work on this together.

**Comment by adj-dev** [comment]
UPDATE: I resolved this issue in my local version, still mulling over it before making my PR.
