### ISSUE TITLE
assignee property on tasks is not populating

### ISSUE THREAD

**Issue by adj-dev** [adj-dev/final-project#74]
I was under the impression that assignee would be populated on the user object but I'm not having any luck with it. I'm wondering if it has to do with the fact that in the Task schema the assignee is set to an object that holds the objectId and not an array of objects? If this issue proves to be too much trouble to fix I can provide solutions on the front-end, but I already have a lot to get working smooth before tuesday

**Comment by zekkxx** [comment]
Fixed with PR #78
